version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    env_file:
      - .docker.env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .docker.env

  main-service:
    container_name: main-service
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .docker.env
    command: bash -c "alembic upgrade head && uvicorn src.views:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
      - rabbitmq
