version: "3"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
