"""add user model

Revision ID: b830d9e47518
Revises: 
Create Date: 2022-09-16 17:41:21.117413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b830d9e47518'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REGULAR', name='userrole'), nullable=True),
    sa.Column('second_name', sa.String(length=512), nullable=False),
    sa.Column('updated_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')

    userrole = postgresql.ENUM('ADMIN', 'REGULAR', name='userrole')
    userrole.drop(op.get_bind())
    # ### end Alembic commands ###
